    # Step 6: Deploy Docker image to EC2
    - name: Deploy Docker image
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOSTNAME: ${{ vars.HOSTNAME }}
        USERNAME: ${{ vars.USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} << EOF
          # Pull the latest Docker image
          docker pull gabrielsonnino/java-app:latest

          # Stop and remove the existing container if it exists
          docker stop java-app || true
          docker rm java-app || true

          # Start a new container
          docker run -d --name java-app -p 8080:8080 gabrielsonnino/java-app:latest

        EOF

