name: Maven Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Install the correct Maven version
    - name: Install Maven 3.9.2
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
        tar xzvf apache-maven-3.9.2-bin.tar.gz
        sudo mv apache-maven-3.9.2 /opt/maven
        sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
      shell: bash

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Build the project
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Publish to GitHub Packages Apache Maven
    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

